### ISSUE TITLE
Cannot compile with musl as target

### ISSUE THREAD

**Issue by Keats** [compass-rs/sass-rs#30] opened 2018-07-17 10:25 UTC
See https://github.com/Keats/gutenberg/issues/316

In short:

Root issue: rust-lang/rust#36710
Related (?) RFC: https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md
Current merged solution: rust-lang/rust#51063

**Comment by mitchtbaum** [comment] 2018-11-21 04:05
Linked root issue and merged issue are closed.  Is this done?

**Comment by Keats** [comment] 2018-11-21 13:02
It didn't work before even with the issue merged, haven't tried recently.
Someone could try to run the dockerfile from https://github.com/getzola/zola/issues/316 with the latest Rust to see if it works

**Comment by greizgh** [comment] 2019-01-19 11:21
This issue seems to be reproduced when trying to build the example with musl:
```
alias rust-musl-builder='docker run --rm -it -v "$(pwd)":/home/rust/src messense/rust-musl-cross:x86_64-musl'
rust-musl-builder cargo run --example compile_sass
```

**Comment by izelnakri** [comment] 2019-11-16 18:34
How can we make this work with Docker/musl? Is there any example `Dockerfile`'s?

**Comment by Keats** [comment] 2019-11-16 19:32
I have no idea, I'd be happy if someone figures it out.

**Comment by izelnakri** [comment] 2019-11-17 08:43
I found the solution, my container(s) were missing make and perhaps other system dependencies however the error were "saying file is not found" instead. Even an archlinux setup with libsass package can give the same error when make package is not installed. Can we make build.rs give better error messages?

**Comment by DusterTheFirst** [comment] 2020-04-04 22:38
@Keats Does your system have git installed? By adding RUST_BACKTRACE to my build, I found line 56 (https://github.com/compass-rs/sass-rs/blob/master/sass-sys/build.rs#L56) as the culprit, and installing git fixed the problem for me

**Comment by shalzz** [comment] 2020-04-05 13:46
@DusterTheFirst The issue is the libsass_sys still relies on glibc when build on a musl target.
You can test this when building on a musl distro like `alpine` or `clux/muslrust`

Here is the latest error I got when build libsass (as a dependency of zola)
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-m64" "-nostdlib" "/root/.rustup/toolchains/stable-2020-03-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/crt1.o" "/root/.rustup/toolchains/stable-2020-03-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/crti.o" "-L" "/root/.rustup/toolchains/stable-2020-03-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib" "/volume/zola/target/x86_64-unknown-linux-musl/release/deps/zola-968e9cfc378e8f2f.zola.alpi785d-cgu.0.rcgu.o" "-o" "/volume/zola/target/x86_64-unknown-linux-musl/release/deps/zola-968e9cfc378e8f2f" "-Wl,--gc-sections" "-no-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/volume/zola/target/x86_64-unknown-linux-musl/release/deps" "-L" "/volume/zola/target/release/deps" "-L" "/volume/zola/target/x86_64-unknown-linux-musl/release/build/onig_sys-0e0b3f18c88aaec8/out" "-L" "/volume/zola/target/x86_64-unknown-linux-musl/release/build/ring-e6b213b30851ee3d/out" "-L" "/musl/lib" "-L" "/volume/zola/target/x86_64-unknown-linux-musl/release/build/sass-sys-46c51feb898fb45f/out/build/lib" "-L" "/root/.rustup/toolchains/stable-2020-03-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/tmp/rustcRfKRWT/libring-618a352d682617ed.rlib" "/tmp/rustcRfKRWT/libopenssl_sys-226e7cfe5dfe39f7.rlib" "/tmp/rustcRfKRWT/libsass_sys-db0c88bd4bf3fed9.rlib" "/tmp/rustcRfKRWT/libonig_sys-bc9463563034fbd4.rlib" "-Wl,--start-group" "/tmp/rustcRfKRWT/libbacktrace_sys-9a97763b2b5e5e63.rlib" "/tmp/rustcRfKRWT/libunwind-984beb1d09763686.rlib" "/tmp/rustcRfKRWT/liblibc-6c4492b949101b15.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-2020-03-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-c9fca8d265033410.rlib" "-Wl,-Bdynamic" "-lstdc++" "-static" "/root/.rustup/toolchains/stable-2020-03-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/crtn.o"
  = note: /usr/bin/ld: /tmp/rustcRfKRWT/libsass_sys-db0c88bd4bf3fed9.rlib(json.o): undefined reference to symbol '__fprintf_chk@@GLIBC_2.3.4'
          //lib/x86_64-linux-gnu/libc.so.6: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
```

For reference here is the Dockerfile I'm using
```dockerfile
ARG RUSTC_VERSION=1.42.0

FROM clux/muslrust:${RUSTC_VERSION}-stable as builder
#FROM rust:${RUSTC_VERSION}-slim-stretch as builder

ENV ZOLA_VERSION 0.10.1

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
    wget

RUN wget https://github.com/getzola/zola/archive/v${ZOLA_VERSION}.tar.gz && \
    mkdir zola && \
    tar -zxvf v${ZOLA_VERSION}.tar.gz -C zola && \
    mv zola/zola-${ZOLA_VERSION}/* zola/ && \
    rm -f v${ZOLA_VERSION}.tar.gz

WORKDIR zola

ENV RUST_BACKTRACE=1

RUN cargo build --release

FROM alpine

COPY --from=builder /zola/target/release/zola /usr/local/bin/

CMD ["zola"]
```

**Comment by DusterTheFirst** [comment] 2020-04-05 13:51
@Shalzz I was able to build and run sass-sys on alpine. 

Here’s the docker file I used. 


https://github.com/DusterTheFirst/sxfs/blob/master/Dockerfile

**Comment by Elinvynia** [comment] 2020-05-31 16:41
Is there any way to compile this fully statically to be used in a `scratch` container?

**Closed** 2023-02-26 19:18 UTC
